services:
  auth-service:
    build: ./services/auth-service
    ports:
      - "8001:8000"
    volumes:
      - ./services/auth-service/app:/usr/src/app/app
    env_file:
      - ./services/auth-service/.env

  crm-service:
    build: ./services/crm-service
    ports:
      - "8002:8000"
    volumes:
      - ./services/crm-service/app:/usr/src/app/app

  analytics-service:
    build: ./services/analytics-service
    ports:
      - "8003:8000"
    volumes:
      - ./services/analytics-service/app:/app/app

  maps-service:
    build: ./services/maps-service
    ports:
      - "8004:3000"
    volumes:
      - ./services/maps-service:/usr/src/app
      - /usr/src/app/node_modules

  notifications-service:
    build: ./services/notifications-service
    ports:
      - "8005:8000"
    volumes:
      - ./services/notifications-service/app:/app/app

  mcp-service:
    build: ./services/mcp-service
    ports:
      - "8006:8000"
    volumes:
      - ./services/mcp-service/app:/app/app

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: