services:
  auth-service:
    build: ./services/auth-service
    image: agoraelectoral/auth-service:latest
    ports:
      - "8001:8000"
    volumes:
      - ./services/auth-service/app:/app/app
    env_file:
      - ./services/auth-service/.env

  crm-service:
    build: ./services/crm-service
    image: agoraelectoral/crm-service:latest
    ports:
      - "8002:8000"
    volumes:
      - ./services/crm-service/app:/app/app
    env_file:
      - ./services/crm-service/.env

  analytics-service:
    build: ./services/analytics-service
    image: agoraelectoral/analytics-service:latest
    ports:
      - "8003:8000"
    volumes:
      - ./services/analytics-service/app:/app/app
    env_file:
      - ./services/analytics-service/.env

  maps-service:
    build: ./services/maps-service
    image: agoraelectoral/maps-service:latest
    ports:
      - "8004:3000"
    env_file:
      - ./services/maps-service/.env

  notifications-service:
    build: ./services/notifications-service
    image: agoraelectoral/notifications-service:latest
    ports:
      - "8005:8000"
    volumes:
      - ./services/notifications-service/app:/app/app
    env_file:
      - ./services/notifications-service/.env

  mcp-service:
    build: ./services/mcp-service
    image: agoraelectoral/mcp-service:latest
    volumes:
      - ./services/mcp-service/app:/app/app
    env_file:
      - ./services/mcp-service/.env

  frontend:
    build:
      context: ./frontend
      args:
        VITE_CRM_SERVICE_URL: http://localhost:8002
        VITE_AUTH_SERVICE_URL: http://localhost:8001
    image: agoraelectoral/frontend:latest
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: