[build]
  command = "npm run build"
  publish = "dist"

# Redirecciones (opcional, pero útil para SPAs como React Router)
# Si usas React Router con BrowserRouter, esto es crucial para que las rutas funcionen al recargar la página
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
