apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: gcr.io/YOUR_GCP_PROJECT_ID/auth-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: SUPABASE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets # This secret needs to be created in K8s
              key: SUPABASE_JWT_SECRET
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials # This secret needs to be created in K8s
              key: DATABASE_URL
