apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-service-deployment
  labels:
    app: crm-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crm-service
  template:
    metadata:
      labels:
        app: crm-service
    spec:
      containers:
      - name: crm-service
        image: gcr.io/YOUR_GCP_PROJECT_ID/crm-service:latest
        ports:
        - containerPort: 8000
