apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-service-deployment
  labels:
    app: crm-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crm-service
  template:
    metadata:
      labels:
        app: crm-service
    spec:
      containers:
      - name: crm-service
        image: gcr.io/YOUR_GCP_PROJECT_ID/crm-service:__IMAGE_TAG__ # Tag updated by CI/CD
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: / # Assuming root path returns 200 OK
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
