apiVersion: apps/v1
kind: Deployment
metadata:
  name: maps-service-deployment
  labels:
    app: maps-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maps-service
  template:
    metadata:
      labels:
        app: maps-service
    spec:
      containers:
      - name: maps-service
        image: gcr.io/YOUR_GCP_PROJECT_ID/maps-service:__IMAGE_TAG__ # Tag updated by CI/CD
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_HOST
          value: "redis"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: / # Assuming root path returns 200 OK
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 25
          periodSeconds: 25
          timeoutSeconds: 5
          failureThreshold: 3
