apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-service-deployment
  labels:
    app: mcp-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-service
  template:
    metadata:
      labels:
        app: mcp-service
    spec:
      containers:
      - name: mcp-service
        image: gcr.io/YOUR_GCP_PROJECT_ID/mcp-service:latest # REPLACE with your actual image path
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis"
