apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-service-deployment
  labels:
    app: mcp-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-service
  template:
    metadata:
      labels:
        app: mcp-service
    spec:
      containers:
      - name: mcp-service
        image: gcr.io/YOUR_GCP_PROJECT_ID/mcp-service:__IMAGE_TAG__ # Tag updated by CI/CD
        env:
        - name: REDIS_HOST
          value: "redis"
        resources:
          requests:
            memory: "128Mi"  # Python script, depends on its processing
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        # Readiness probe might not be applicable for a stdio script without a specific ready state,
        # or would need a custom solution (e.g., script creates a file when ready).
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep '[p]oetry run python app/main.py' | grep -v grep"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
